### ISSUE TITLE
Image is twisted

### ISSUE THREAD

**Issue by rieders** [jomjol/water-meter-measurement-system#2]
Hello.
I am trying to try this very nice project. I have 2 problems. One is that I can't adjust the light of the LED (brightness). The other is that the picture sometimes twists. I have already recreated the reference image several times. Unfortunately, I only have 2 reference brands. I can't create a 3rd brand. Maybe that's the reason.

Thank you for the help

**Comment by jomjol** [comment]
Hi,
the LED brightness cannot be adjusted. Currently there is no PWM implemented. But anyway, the camera is running in automode, so if you decrease the brightness, the camera will compensate for this.

I would strongly recommend to change to the new all-in-one version: https://github.com/jomjol/AI-on-the-edge-device

This repository is not maintained and update since quite some time.
